#Fill in your MySQL details
mysql:
    host: localhost
    port: 3306
    database: database
    username: username
    password: password

#Time between updates for all online players in seconds
#(online status is updated immediately)
frequency: 600