name: MinecraftStatistics
version: 3.0
author: Zethrus fork, original author is Zander van der Meer
main: minecraftstatistics.Main
website: https://minersglory.com
commands:
    statSync:
        description: Sync stats of all players currently online
        permission: minecraftstatistics.sync
        default: op
        usage: /statsync