#Fill in your MySQL details
mysql:
    host: localhost
    port: 3306
    database: database
    username: username
    password: password
    table: stats

#Time between updates for all online players in seconds
#(online status is updated immediately)
frequency: 600

#Server name, can be used to use a single table for multiple servers
servername: default